### ISSUE TITLE
Z-bottom and Z-top

### ISSUE THREAD

**Issue by basileh** [smithsg84/pf-mask-utilities#1]
Hello Steve,
Thanks for the tool, it's very convenient and makes life easier for PF users!
since PF is mostly used in terrain following, do you think you could add two arguments to the program command to let the user specify an altitude for the 'bottom' and 'top' vertices ? 
I've noticed you added a --depth option (not mentioned in the readme.md though), but that still fixes the bottom elevation value to 0, and some users might want other values.
Thanks much!
Basile

**Comment by smithsg84** [comment]
These utilities have been moved to the main Parflow repository as part of pftools.

z-top and z-bottom are now arguments to the pfmask-to-pfsol utility to set the top and bottom.
