### ISSUE TITLE
non-0 x corner & y corner

### ISSUE THREAD

**Issue by basileh** [smithsg84/pf-mask-utilities#2]
Hello, 
in my case my south - West corner coordinates are not 0's, and I have to add an X and a Y offset to the vertices coordinates in the pfsol output from your code in order for PF to run.

Since your code requires an .asc mask file with the header containing:
xllcorner 0.0 yllcorner 0.0
is it possible to add up some lines in your code to propagate non-0 values through the process to have correct pfsol's vertice coordinates?
Many thanks!

Basile

**Comment by smithsg84** [comment]
These utilities have been merged into main Parflow code.

The x/y corner should now be propagated to the solid file.
